spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: "{baseScheme}://{baseHost}{basePort}/login/oauth2/code/{registrationId}"
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_name // vars to replace is db_name
    username: user
    password: pass
  main:
    web-application-type: reactive
logging:
  level:
    root: DEBUG or INFO
project:
  dev:
    csrf: true
    frontend:
      url: frontendUrl
server:
  port: 8000
  ssl:
    key-store: classpath:nameOfKeystoreFile
    key-store-password: KeyStorePass
    key-store-type: KeyStoreType
    key-alias: alias


